[functions]
  external_node_modules = ["express", "axios", "cheerio", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/scraper"
  status = 200
  force = true
